### PR TITLE
delete isNpm()

### PR DESCRIPTION
**Pull request by dnxbf321**
npm run script should be work now

### CODE REVIEW

**Comment by sindresorhus** [comment]
You can't just delete stuff without looking into why it was added. Everything is added for a reason.

**Comment by vincentmorneau** [comment]
As discussed [here](https://github.com/yeoman/update-notifier/issues/92), I'm also interested in knowing why `isNPM` is being used?

**Comment by sindresorhus** [comment]
`git blame` the relevant code.

**Comment by vincentmorneau** [comment]
`git blame` wasn't revelant due to multiple code changes, but [this commit ](https://github.com/yeoman/update-notifier/commit/b287a6dd79eabc9cd378999087d3ab541c171df4) is what introduced the issue conflicting with Gulp.

**Comment by nexdrew** [comment]
See my attempt at an explanation here: https://github.com/yeoman/update-notifier/issues/92#issuecomment-238997309

**Comment by dnxbf321** [comment]
Thanks a lot, but my project is run with npm scripts, i need combine mutil

**Pull request closed without merging**
