### PR TITLE
feat(core): addInstallCommandMessage

### PR DESCRIPTION
**Pull request by andreasonny83**
`addInstallCommandMessage` option to be used in combination with the
`message` option to append the installation command instructions to the notification.

## Why

When using `update-notifier`, sometimes I want to generate a different message to be displayed in the notification. However, the installation instruction provided by `update-notifier` is quite useful and I would like to benefit from that instead of duplicating the logic in all my packages.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Can you provide an example of what exactly you would use it for? What kind of extra message?

**Comment by andreasonny83** [comment]
Thanks for the attention @sindresorhus .
I hoped the implementation was quite self explanatory considering that I updated the README accordingly.
However, this is how I would use it in my projects:

```
notifier.notify({
  message: 'My new message without install message 😢 ',
  addInstallCommandMessage: true // 😄 This will bring the install message back to the notification message
});
```

Let me know if that makes sense to you.

Thanks!

**Comment by sindresorhus** [comment]
It's not the implementation that is unclear. I was asking about what **message** you would use? I'm curious what other information you would want to show in the update notification? Let say I'm a update-notifier user, and I see this new option, and I wonder "hmm, what should I use this for?", some examples in the docs would go a long way. So instead of explaining it here, add some example messages to the readme.

**Comment by sindresorhus** [comment]
Instead of adding an option that changes the behavior of the `message` option. I think it would be better to just make this new option accept a string for the additional message. It would need a new name.

**Comment by andreasonny83** [comment]
actually I included an example and a screenshot to the documentation. It should be pretty clear how to use it and what it does

**Comment by andreasonny83** [comment]
any update on this PR @sindresorhus ? If you're not happy with the changes, just close it.
Thanks again

**Comment by andreasonny83** [comment]
Just to recap @sindresorhus . 
Before this PR, to display this message:
```
   ╭───────────────────────────────────────────────╮
   │                                               │
   │               Update available                │
   │   Run npm i -g twilio-remote-cli to update    │
   │                                               │
   ╰───────────────────────────────────────────────╯
```

The code required was:
```
if (notifier.update) {
  const installCommand = `npm i -g ${notifier.update.name}`;
  const messageCopy =
    `Update available` +
    `Run ${chalk.cyan(installCommand)} to update`;

  notifier.notify({ message: messageCopy });
}
```

After this PR:
```
notifier.notify({ message: 'Update available', addInstallCommandMessage: true });
```

**Comment by fisker** [comment]
I didn't see this before I send #175 .

@andreasonny83 What do you think of #175, it should work in your case too, like this

```js
notifier.notify({ message: 'Update available\nRun {command} to update'});
```

**Comment by andreasonny83** [comment]
Thank you @fisker . Yes, that looks great.

**Comment by sindresorhus** [comment]
https://github.com/yeoman/update-notifier/releases/tag/v4.1.0

**Comment by andreasonny83** [comment]
Great! Thanks

**Pull request closed without merging**
