### PR TITLE
Don't suggest to upgrade to lower version

### LINKED ISSUE #181: It just suggested a version downgrade to me
Screenshot:

image

As text:

```
$ npx xo --fix


   ╭───────────────────────────────────────╮
   │                                       │
   │   Update available 0.32.0 → 0.30.0    │
   │        Run npm i xo to update         │
   │                                       │
   ╰───────────────────────────────────────╯

```

What is happening? :sweat_smile:

### PR DESCRIPTION
**Pull request by fregante**
Fixes #181 

I haven't investigated why this would happen in the first place, but I guess it could if you install a beta version.

Is that a bug in https://github.com/sindresorhus/latest-version?

### CODE REVIEW

**Comment by sindresorhus** [comment]
> Is that a bug in sindresorhus/latest-version?

Not sure, but I don't think so, since I've seen this problem happen on non-beta versions too.

**Comment by fregante** [comment]
Yeah the 2 comments were unrelated. I think latest-version could return a version older than its supposed to, I don’t know what else could be happening. Is it still cached here?

**Comment by slorber** [comment]
Hi,

Not sure it's related but we got those messages reported here:

image

https://github.com/facebook/docusaurus/issues/4782

Any idea what could be happening?

**Comment by slorber** [comment]
Looks like this bug is caused by the async nature of this package: fetch the update, and only notify about it on the 2nd run.

As I have my own code to notify users, I think I should just backport your logic to my own notifier.

Wouldn't it make sense to somehow "erase" this.update data if on 2nd run we detech packageVersion is > latest fetched version? This could fix the issue in a more generic way?

**Pull request merged**
