### PR TITLE
Add is-installed-globally for auto-detection

### PR DESCRIPTION
**Pull request by tdeschryver**
See #112 (and avajs/ava#1407)

### CODE REVIEW

**Comment by nexdrew** [comment]
These changes LGTM, assuming we consider `is-installed-globally@0.1.0` (and `global-dirs@0.1.0`) to be stable. Based on my testing with Node 8/npm 5 and [this commit](https://github.com/sindresorhus/is-installed-globally/commit/6743bb1d181252f0e6f67f2cd4d54ed213961e54), I'm not sure we're ready to do that.

@sindresorhus Perhaps you can elaborate a bit (or point us to an issue) on the current problem with npm 5? Looks like npm 5 symlinks "global installs of a local package" into the global root (i.e. result of `npm root --global`) instead of copying the package there (as it did in npm 4)?

**Comment by sindresorhus** [comment]
> assuming we consider `is-installed-globally@0.1.0` (and `global-dirs@0.1.0`) to be stable.

It works from my local testing and the tests, but there might be edge-cases I haven't considered. I wouldn't say it's that important though. Worst case, it shows the wrong install flag and we fix it. It already shows the wrong flag when installed locally, so it's not like it would be worse. Happy to keep this open for a little bit so people can try it out though.

> Looks like npm 5 symlinks "global installs of a local package" into the global root (i.e. result of `npm root --global`) instead of copying the package there (as it did in npm 4)?

Yes, I have a todo to open an issue on the npm issue tracker about it.

**Comment by sindresorhus** [comment]
@tdeschryver Can you fix the merge conflict?

**Comment by tdeschryver** [comment]
No problemo!

**Comment by sindresorhus** [comment]
Thanks :)

**Pull request merged**
