### PR TITLE
Run tests on Node.js 8

### PR DESCRIPTION
**Pull request by SimenB**
Tests fail on node 8 locally for me.

image

### CODE REVIEW

**Comment by sindresorhus** [comment]
Would you be able to look into why it's failing?

**Comment by SimenB** [comment]
@sindresorhus `caller-path` returns `null`.

https://github.com/sindresorhus/caller-path/blob/622c284b4aa5f8757283dbd494d0f39b5528f7d9/index.js#L4

Which comes from the fact that the callsite returned by `caller-callsite` is `Array.forEach (<anonymous>)`(https://github.com/sindresorhus/caller-callsite/blob/1ce43fc89a890a702f5da866ed151b14e2ff54e5/index.js#L12)

_Why_ this happens, I don't know... I don't understand why `caller-callsite` does what it does, so can't really dig any more than that. Full stack in `caller-callsite` is (doing `.map(::toString).join('\n')`):

```
module.exports (/Users/simen/Development/update-notifier/node_modules/caller-callsite/index.js:5:12)
module.exports (/Users/simen/Development/update-notifier/node_modules/caller-path/index.js:5:19)
clear (/Users/simen/Development/update-notifier/node_modules/clear-module/index.js:11:12)
Array.forEach (<anonymous>)
Test._ava2.default.before [as fn] (/Users/simen/Development/update-notifier/test/fs-error.js:30:38)
Test.callFn (/Users/simen/Development/update-notifier/node_modules/ava/lib/test.js:305:18)
Test.run (/Users/simen/Development/update-notifier/node_modules/ava/lib/test.js:318:23)
runNext (/Users/simen/Development/update-notifier/node_modules/ava/lib/sequence.js:58:44)
Sequence.run (/Users/simen/Development/update-notifier/node_modules/ava/lib/sequence.js:90:10)
runNext (/Users/simen/Development/update-notifier/node_modules/ava/lib/sequence.js:58:44)
Sequence.run (/Users/simen/Development/update-notifier/node_modules/ava/lib/sequence.js:90:10)
Bluebird.try (/Users/simen/Development/update-notifier/node_modules/ava/lib/runner.js:221:48)
tryCatcher (/Users/simen/Development/update-notifier/node_modules/bluebird/js/release/util.js:16:23)
Function.Promise.attempt.Promise.try (/Users/simen/Development/update-notifier/node_modules/bluebird/js/release/method.js:39:29)
Runner.run (/Users/simen/Development/update-notifier/node_modules/ava/lib/runner.js:221:22)
process.on.options (/Users/simen/Development/update-notifier/node_modules/ava/lib/main.js:83:10)
emitOne (events.js:115:13)
process.emit (events.js:210:7)
processEmit [as emit] (/Users/simen/Development/update-notifier/node_modules/signal-exit/index.js:155:32)
Immediate.setImmediate (/Users/simen/Development/update-notifier/node_modules/ava/profile.js:139:13)
runCallback (timers.js:781:20)
tryOnImmediate (timers.js:743:5)
processImmediate [as _immediateCallback] (timers.js:714:5)"
```

**Comment by SimenB** [comment]
A "fix" is to add a `c[i].getFileName() !== null` in `caller-callsite`, and this diff in `update-notifier`:

```diff
diff --git i/test/fs-error.js w/test/fs-error.js
index 1d0d4cd..e325dbd 100644
--- i/test/fs-error.js
+++ w/test/fs-error.js
@@ -4,7 +4,7 @@ import test from 'ava';
 let updateNotifier;
 
 test.before(() => {
-	['.', 'configstore', 'xdg-basedir'].forEach(clearModule);
+	['..', 'configstore', 'xdg-basedir'].forEach(clearModule);
 	// Set configstore.config to something
 	// that requires root access
 	process.env.XDG_CONFIG_HOME = '/usr';
diff --git i/test/notify.js w/test/notify.js
index ab24d5d..8f92bf0 100644
--- i/test/notify.js
+++ w/test/notify.js
@@ -10,7 +10,7 @@ const stderr = new FixtureStdout({
 let updateNotifier = require('..');
 
 test.before(() => {
-	['.', 'is-npm'].forEach(clearModule);
+	['..', 'is-npm'].forEach(clearModule);
 	['npm_config_username', 'npm_package_name', 'npm_config_heading'].forEach(name => {
 		delete process.env[name];
 	});
```

**Comment by sindresorhus** [comment]
The problem mentioned in this PR has since been fixed. Although, there's something else not passing now: https://github.com/yeoman/update-notifier/issues/153

**Pull request closed without merging**
